services:
  - type: web
    name: rt-idps-dashboard
    env: python
    plan: free
    buildCommand: pip install --no-cache-dir --only-binary=:all: -r requirements.txt
    startCommand: gunicorn dashboard.app:app --bind 0.0.0.0:$PORT --workers 1 --timeout 120
    autoDeploy: true
    envVars:
      - key: PIP_ONLY_BINARY
        value: ":all:"
