#!/usr/bin/env python3
"""
Utility script to generate secure credentials for production deployment
"""

import sys
import os
import secrets
from pathlib import Path

# Add parent directory to path
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

try:
    from werkzeug.security import generate_password_hash
except ImportError:
    print("Error: werkzeug is not installed. Install it with: pip install werkzeug")
    sys.exit(1)


def generate_secret_key():
    """Generate a secure secret key"""
    return secrets.token_hex(32)


def generate_password_hash_cli(password):
    """Generate a secure password hash"""
    return generate_password_hash(password, method='pbkdf2:sha256')


def main():
    print("=" * 70)
    print("RT-IDPS Production Credentials Generator")
    print("=" * 70)
    print()

    # Generate secret key
    print("1. Generating SECRET_KEY...")
    secret_key = generate_secret_key()
    print(f"   SECRET_KEY={secret_key}")
    print()

    # Generate admin password hash
    print("2. Generating ADMIN_PASSWORD_HASH...")
    print("   Enter admin password (minimum 8 characters recommended):")
    password = input("   > ").strip()

    if not password:
        print("   Error: Password cannot be empty")
        sys.exit(1)

    if len(password) < 6:
        print("   Warning: Password is very short (less than 6 characters)")
        confirm = input("   Continue anyway? (y/n): ").strip().lower()
        if confirm != 'y':
            sys.exit(1)

    password_hash = generate_password_hash_cli(password)
    print(f"   ADMIN_PASSWORD_HASH={password_hash}")
    print()

    # Display complete .env configuration
    print("=" * 70)
    print("Add these to your .env file (or set as environment variables):")
    print("=" * 70)
    print()
    print(f"SECRET_KEY={secret_key}")
    print(f"ADMIN_PASSWORD_HASH={password_hash}")
    print("FLASK_HOST=0.0.0.0")
    print("FLASK_PORT=5000")
    print("FLASK_DEBUG=False")
    print("ADMIN_USERNAME=admin")
    print("NETWORK_INTERFACE=eth0")
    print("CORS_ORIGINS=*")
    print("LOG_LEVEL=INFO")
    print()

    # Optionally save to .env file
    print("=" * 70)
    env_path = Path(__file__).parent / ".env"
    save_to_file = input("Save to .env file? (y/n): ").strip().lower()

    if save_to_file == 'y':
        if env_path.exists():
            overwrite = input(f"   {env_path} already exists. Overwrite? (y/n): ").strip().lower()
            if overwrite != 'y':
                print("   Skipped saving to file.")
                sys.exit(0)

        # Load existing .env if present
        env_content = {}
        if env_path.exists():
            with open(env_path, 'r') as f:
                for line in f:
                    line = line.strip()
                    if line and not line.startswith('#') and '=' in line:
                        key, value = line.split('=', 1)
                        env_content[key.strip()] = value.strip()

        # Update with new values
        env_content['SECRET_KEY'] = secret_key
        env_content['ADMIN_PASSWORD_HASH'] = password_hash
        env_content['FLASK_HOST'] = env_content.get('FLASK_HOST', '0.0.0.0')
        env_content['FLASK_PORT'] = env_content.get('FLASK_PORT', '5000')
        env_content['FLASK_DEBUG'] = env_content.get('FLASK_DEBUG', 'False')
        env_content['ADMIN_USERNAME'] = env_content.get('ADMIN_USERNAME', 'admin')
        env_content['NETWORK_INTERFACE'] = env_content.get('NETWORK_INTERFACE', 'eth0')
        env_content['CORS_ORIGINS'] = env_content.get('CORS_ORIGINS', '*')
        env_content['LOG_LEVEL'] = env_content.get('LOG_LEVEL', 'INFO')

        # Write to file
        with open(env_path, 'w') as f:
            f.write("# RT-IDPS Production Environment Variables\n")
            f.write("# Generated by setup_credentials.py\n\n")
            for key, value in env_content.items():
                f.write(f"{key}={value}\n")

        print(f"   ✓ Saved to {env_path}")
        print()
        print("IMPORTANT: Keep .env file secure and never commit it to version control!")
        print()
    else:
        print("   Skipped saving to file.")
        print("   You can manually add these values to your .env file or set them as environment variables.")
        print()


if __name__ == '__main__':
    try:
        main()
    except KeyboardInterrupt:
        print("\nCancelled.")
        sys.exit(1)
